# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
---
include:
  - board: nice_nano_v2 
    shield: sofle_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2 
    shield: sofle_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: sofle_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: sofle_right
  - board: nice_nano_v2
    shield: settings_reset